### ISSUE TITLE
Documentation: Full list of built in messages and how to override them

### ISSUE THREAD

**Issue by Nrde** [tanepiper/svelte-formula#15]
I'm tying to localize some error messages like for example "tooShort" message.

Please use at least XX characters (you are currently using Y characters). 

How can I get the inputs min and maxlength to construct the message above to the tooShort message. Probably a stupid mistake as I get the full string and not the result when I use:

```messages: {
      description: {
          tooShort: (value) => value.length > 19 ? null : `write at least 20 characters. (you have written '+value.length+' characters.)`
      }
 }

**Comment by tanepiper** [comment]
If I get you, you want the `19` in the condition to come from the element? There isn't a way just now to do this directly in Formula

You could possibly write your own selector for the field to get the value and pass it?

```
const el = document.getElementByName('description')
```

Then use `el.getAttribute('maxlength')` possibly?  Haven't tried it but could work for your case

**Comment by Nrde** [comment]
Ok, I can try that, but where does the default message for "tooShort" come from? Is it a browser built in message for html5 form?

**Comment by Nrde** [comment]
The bigger problem is actually that the message is replaced with the complete function.

I.e., when the message is supposed to be displayed it displays:
(value) => value.length > 19 ? null : `write at least 20 characters. (you have written '+value.length+' characters.)`

**Comment by tanepiper** [comment]
Hi @Nrde apologies I didn't get around to answering you - did you resolve your issue? I'll close the issue but if you need to please feel free to reopen it and we can try resolve it
