### ISSUE TITLE
Not able to use the chaining operator "?."

### ISSUE THREAD

**Issue by jonathanblancor** [tanepiper/svelte-formula#23]
I am using Svelte with Sapper and I get the error in the picture when using the `?.` operator to test for nullish.

Is there a reason this is happening or could it be a configuration I am missing?

![image](https://user-images.githubusercontent.com/13365903/119034769-b9401500-b97c-11eb-867c-2b5b5046c018.png)
That line is from the Formula docs.

**Comment by tanepiper** [comment]
Hi @jonathanblancor - What version of Node are you using? It was added in Node 14, and it looks like you're getting a compile error which points to an earlier version: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining

**Comment by jonathanblancor** [comment]
Thank you!
