### ISSUE TITLE
Request: A guide for local development

### ISSUE THREAD

**Issue by benwoodward** [tanepiper/svelte-formula#26]
I'd like to be able to install `svelte-formula` locally, and add `console.log` statements, and potentially create some PRs, but struggling to get this to work locally in SvelteKit. 

I get the following errors: 

```
Cannot find module 'svelte-formula' from '/Users/ben/dev/my-project/src/lib/components/forms'
```

```
Cannot find module 'tinynodes' from '/Users/ben/dev/my-project/src/lib/components/forms'
```

Would be great if there was a step-by-step guide for local development for non-expert JS devs like me. Thanks!

**Comment by nohea** [comment]
this may be beyond the scope of this project. I recommend learning more on node.js, and npm specifically if you want to download a library like this, and debug it locally. Look into npm link.
