### ISSUE TITLE
Documentation not working

### ISSUE THREAD

**Issue by jpet710122** [tanepiper/svelte-formula#28]
Error: Your Docusaurus site did not load properly.

A very common reason is a wrong site [baseUrl configuration](https://v2.docusaurus.io/docs/docusaurus.config.js/#baseurl).

Current configured baseUrl = / (default value)

We suggest trying baseUrl = /svelte-formula/

svelte-formula (+ Beaker) seems like what I've been looking for, but I need to see the docs!

**Comment by tanepiper** [comment]
Hi @jpet710122 I'm aware of this - I did try to update it, but it now fails to build and I haven't had time to fix it as it's a dependency issue.  If you download the repo you can try run `npm docs` and see if it builds for you locally

**Comment by jpet710122** [comment]
Downloaded the repo and tried to build locally, but no luck.

**Comment by fabien** [comment]
I had the same problem, but this worked for me after changing the `baseUrl` in `docusaurus.config.js`:

```
npm i --legacy-peer-deps
npm run docs
serve docs
```

Note that `serve` here is https://www.npmjs.com/package/serve - I had trouble with the suggested `npm run serve`. Hope this helps! Would be nice to have the docs up online again though ...

**Comment by tanepiper** [comment]
@fabien Thank you! That's fixed it and docs now deployed on the github pages URL!

**Comment by fabien** [comment]
@tanepiper thanks! I actually forked the project to fix a bug in Beaker/groups: https://github.com/fabien/svelte-formula/blob/0e060c04dce758d8be6eac780dc75e73b71422cf/packages/svelte/formula/src/lib/group/group.ts

Didn't really mean to fork and maintain it on my own though, but I figured the project was a bit stalled so I went ahead. Please let me know if you accept a proper PR instead.

**Comment by tanepiper** [comment]
@fabien Yes please! Happy to accept and release this weekend

**Comment by fabien** [comment]
@tanepiper done! Thanks!
