### ISSUE TITLE
async validation support

### ISSUE THREAD

**Issue by sysmat** [tanepiper/svelte-formula#31]
Is possible to have async validation?

**Comment by tanepiper** [comment]
Hey @sysmat - I'm not going to add more features to svelte-formula unless I get PRs. Apart from Svelte stores, its framework agnostic, so when I get time I will most likely look to release a new library with a different store provider.  I do need this myself, so it's likely - just not a priority.

**Comment by sysmat** [comment]
@tanepiper thx, looking forward
