### ISSUE TITLE
Uncaught DOMException: Failed to execute 'querySelectorAll'

### ISSUE THREAD

**Issue by fabien** [tanepiper/svelte-formula#5]
I'm trying to run the examples in the REPL (following your post on reddit) but I keep getting this error in Chrome, even when upping the version to 0.8.6. The culprit is here:

https://github.com/tanepiper/svelte-formula/blob/73f3b3f4d40bcc2e74bbd57342cd8c3fc7f92dda/packages/svelte/formula/src/lib/shared/fields.ts#L11

**Comment by tanepiper** [comment]
Hi @fabien - Can you also post a screenshot or log from the console? Also which demo was it (or was it all?). Also can you try in Incognito mode with no chrome extensions?

**Comment by fabien** [comment]
![image](https://user-images.githubusercontent.com/2749/108870754-b4c3c480-75f8-11eb-8a07-4065740c4de1.png)

Note that this also happens when I simply run `document.querySelectorAll('*[name]:not([role="beaker-group"] *[name])')` in the Chrome console, regardless of being in Incognito (and no extensions) or not. Works fine in Safari though.

**Comment by tanepiper** [comment]
OK, what happens if you just run `*[name]:not([role="beaker-group"] *)` ?

**Comment by tanepiper** [comment]
Just to confirm, both work for me 

![image](https://user-images.githubusercontent.com/376930/108873975-face5780-75fb-11eb-93a3-4e04f3946de3.png)

Edit: Actually, looking at it that's not that I want either :( Will investigate

**Comment by fabien** [comment]
Hi @tanepiper - same thing. What does work is this: `document.querySelectorAll('*[name]:not([role="beaker-group"]) *')` - not sure if that covers the same intent though?

I can imagine that the `not:` pseudo-selector doesn't play nice with `*` because it doesn't actually points to the same element anymore, but any child element instead.

**Comment by tanepiper** [comment]
@fabien OK I've come up with a solution to provide a specific data property to items inside groups, this is now used to filter instead. Published 0.8.7 so should be available on svelte repl now

**Comment by fabien** [comment]
@tanepiper that works, thanks! The demos look interesting!
